-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 19:43:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema databasv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databasv2` DEFAULT CHARACTER SET utf8 ;
USE `databasv2` ;

-- -----------------------------------------------------
-- Table `databasv2`.`customertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`customertype` (
  `CustomerTypeId` INT NOT NULL AUTO_INCREMENT,
  `CustomerType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CustomerTypeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`customer` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(100) NOT NULL,
  `CustomerAddress` VARCHAR(100) NOT NULL,
  `CustomerPhone` VARCHAR(100) NOT NULL,
  `CustomerEmail` VARCHAR(100) NOT NULL,
  `CustomerTypeId` INT NOT NULL,
  PRIMARY KEY (`CustomerId`),
  INDEX `fk_Customer_CustomerType1_idx` (`CustomerTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_CustomerType1`
    FOREIGN KEY (`CustomerTypeId`)
    REFERENCES `databasv2`.`customertype` (`CustomerTypeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`cars` (
  `CarsId` INT NOT NULL AUTO_INCREMENT,
  `CarsRegNo` VARCHAR(100) NOT NULL,
  `CarsManufactor` VARCHAR(100) NOT NULL,
  `CarsModel` VARCHAR(100) NOT NULL,
  `CarsColor` VARCHAR(100) NOT NULL,
  `CustomerId` INT NOT NULL,
  PRIMARY KEY (`CarsId`),
  INDEX `fk_Cars_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `databasv2`.`customer` (`CustomerId`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`personaldata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`personaldata` (
  `PersonalDataId` INT NOT NULL AUTO_INCREMENT,
  `PersonalDataName` VARCHAR(100) NOT NULL,
  `PersonalDataPhone` VARCHAR(100) NOT NULL,
  `PersonalDataEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PersonalDataId`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`manufactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`manufactor` (
  `ManufactorerId` INT NOT NULL AUTO_INCREMENT,
  `ManufactorerName` VARCHAR(100) NOT NULL,
  `ManufactorerAddressHQ` VARCHAR(100) NOT NULL,
  `ManufactoerPhoneHQ` VARCHAR(100) NOT NULL,
  `PersonalDataId` INT NOT NULL,
  PRIMARY KEY (`ManufactorerId`),
  INDEX `fk_Manufactor_ContactPerson1_idx` (`PersonalDataId` ASC) VISIBLE,
  CONSTRAINT `fk_Manufactor_ContactPerson1`
    FOREIGN KEY (`PersonalDataId`)
    REFERENCES `databasv2`.`personaldata` (`PersonalDataId`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`supplier` (
  `SupplierId` INT NOT NULL AUTO_INCREMENT,
  `SupplierName` VARCHAR(100) NOT NULL,
  `SupplierAddress` VARCHAR(100) NOT NULL,
  `SupplierPhone` VARCHAR(100) NOT NULL,
  `SupplierEmail` VARCHAR(100) NOT NULL,
  `PersonalDataId` INT NOT NULL,
  PRIMARY KEY (`SupplierId`),
  INDEX `fk_Supplier_ContactPerson1_idx` (`PersonalDataId` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_ContactPerson1`
    FOREIGN KEY (`PersonalDataId`)
    REFERENCES `databasv2`.`personaldata` (`PersonalDataId`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`sparepart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`sparepart` (
  `SparepartId` INT NOT NULL AUTO_INCREMENT,
  `SparepartName` VARCHAR(45) NOT NULL,
  `ManufactorId` INT NOT NULL,
  `SupplierId` INT NOT NULL,
  `SparepartDescription` VARCHAR(10000) NOT NULL,
  PRIMARY KEY (`SparepartId`),
  INDEX `fk_Sparepart_Manufactor1_idx` (`ManufactorId` ASC) VISIBLE,
  INDEX `fk_Sparepart_Supplier1_idx` (`SupplierId` ASC) VISIBLE,
  CONSTRAINT `fk_Sparepart_Manufactor1`
    FOREIGN KEY (`ManufactorId`)
    REFERENCES `databasv2`.`manufactor` (`ManufactorerId`),
  CONSTRAINT `fk_Sparepart_Supplier1`
    FOREIGN KEY (`SupplierId`)
    REFERENCES `databasv2`.`supplier` (`SupplierId`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`carssparepart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`carssparepart` (
  `CarsID` INT NOT NULL,
  `SparepartId` INT NOT NULL,
  PRIMARY KEY (`CarsID`, `SparepartId`),
  INDEX `fk_Cars_has_Sparepart_Sparepart1_idx` (`SparepartId` ASC) VISIBLE,
  INDEX `fk_Cars_has_Sparepart_Cars1_idx` (`CarsID` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_has_Sparepart_Cars1`
    FOREIGN KEY (`CarsID`)
    REFERENCES `databasv2`.`cars` (`CarsId`),
  CONSTRAINT `fk_Cars_has_Sparepart_Sparepart1`
    FOREIGN KEY (`SparepartId`)
    REFERENCES `databasv2`.`sparepart` (`SparepartId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`store` (
  `StoreId` INT NOT NULL AUTO_INCREMENT,
  `StoreName` VARCHAR(100) NOT NULL,
  `StoreAddress` VARCHAR(100) NOT NULL,
  `StorePhone` VARCHAR(100) NOT NULL,
  `StoreEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`StoreId`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`inventory` (
  `InventoryId` INT NOT NULL AUTO_INCREMENT,
  `StoreId` INT NOT NULL,
  `InventoryLocation` VARCHAR(100) NOT NULL,
  `InventoryQTY` INT NOT NULL,
  `InventoryCriticalLevel` INT NOT NULL,
  `InventoryQTYAutomaticOrder` INT NOT NULL,
  `InventoryETA` VARCHAR(100) NOT NULL,
  `SparepartId` INT NOT NULL,
  PRIMARY KEY (`InventoryId`),
  INDEX `fk_Inventory_Store1_idx` (`StoreId` ASC) VISIBLE,
  INDEX `fk_Inventory_Sparepart1_idx` (`SparepartId` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Sparepart1`
    FOREIGN KEY (`SparepartId`)
    REFERENCES `databasv2`.`sparepart` (`SparepartId`),
  CONSTRAINT `fk_Inventory_Store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `databasv2`.`store` (`StoreId`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`orders` (
  `OrderId` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATE NOT NULL,
  `OrderTime` TIME NOT NULL,
  `StoreId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  PRIMARY KEY (`OrderId`),
  INDEX `fk_Orders_Store1_idx` (`StoreId` ASC) VISIBLE,
  INDEX `fk_Orders_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `databasv2`.`customer` (`CustomerId`),
  CONSTRAINT `fk_Orders_Store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `databasv2`.`store` (`StoreId`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`orderssparepart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`orderssparepart` (
  `OrderId` INT NOT NULL,
  `SparepartId` INT NOT NULL,
  `OrdersAmount` INT NOT NULL,
  PRIMARY KEY (`OrderId`, `SparepartId`),
  INDEX `fk_Orders_has_Sparepart_Sparepart1_idx` (`SparepartId` ASC) VISIBLE,
  INDEX `fk_Orders_has_Sparepart_Orders1_idx` (`OrderId` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Sparepart_Orders1`
    FOREIGN KEY (`OrderId`)
    REFERENCES `databasv2`.`orders` (`OrderId`),
  CONSTRAINT `fk_Orders_has_Sparepart_Sparepart1`
    FOREIGN KEY (`SparepartId`)
    REFERENCES `databasv2`.`sparepart` (`SparepartId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databasv2`.`storeemployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasv2`.`storeemployee` (
  `StoreEmployeeId` INT NOT NULL AUTO_INCREMENT,
  `StoreId` INT NOT NULL,
  `PersonalDataId` INT NOT NULL,
  PRIMARY KEY (`StoreEmployeeId`),
  INDEX `fk_Store_Employee_Store1_idx` (`StoreId` ASC) VISIBLE,
  INDEX `fk_Store_Employee_ContactPerson1_idx` (`PersonalDataId` ASC) VISIBLE,
  CONSTRAINT `fk_Store_Employee_ContactPerson1`
    FOREIGN KEY (`PersonalDataId`)
    REFERENCES `databasv2`.`personaldata` (`PersonalDataId`),
  CONSTRAINT `fk_Store_Employee_Store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `databasv2`.`store` (`StoreId`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
